DROP DATABASE IF EXISTS elyon_db;

CREATE DATABASE IF NOT EXISTS elyon_db;

USE elyon_db;

CREATE TABLE IF NOT EXISTS user (
    uuid VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,

    u_gear INT NOT NULL DEFAULT 0,
    u_level INT NOT NULL DEFAULT 0,
    u_skill INT NOT NULL DEFAULT 0,
    u_class VARCHAR(255) DEFAULT NULL,

    r_red INT NOT NULL DEFAULT 0,
    r_orange INT NOT NULL DEFAULT 0,
    r_yellow INT NOT NULL DEFAULT 0,
    r_blue INT NOT NULL DEFAULT 0,
    r_green INT NOT NULL DEFAULT 0,
    r_purple INT NOT NULL DEFAULT 0
);
